name: ubuntu-image
summary: Create Ubuntu images
description: |
  Use this tool to create Ubuntu images.
version: 0.13+real1
confinement: devmode

apps:
  ubuntu-image:
    command: bin/ubuntu-image

parts:
  ubuntu-image:
    plugin: python
    source: https://github.com/CanonicalLtd/ubuntu-image.git
    source-type: git
    python-packages:
      - attrs
      - voluptuous
      - PyYAML
    snap:
      - bin/ubuntu-image
      - usr
      - lib
      - sbin
    stage-packages:
      - mtools
      - e2fsprogs
      - python3-debian
  snapd:
    plugin: go
    source: https://github.com/snapcore/snapd
    source-type: git
    go-importpath: github.com/snapcore/snapd
    snap:
      - bin/snap
